---
title: "Class 10"
author: "Jesse Rosner"
date: "2026-09-28"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    numbered-sections: TRUE
    code_folding: show
    code_download: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Robotstxt

The code chunk below will show the output from the [robotstxt]() package 
for the ISA course bulletin available at:
<https://bulletin.miamioh.edu/courses-instruction/isa/index.html>

```{r robotstxt}
robotstxt::paths_allowed(paths = "/courses-instruction/isa/", domain = 
"bulletin.miamioh.edu", bot ="*")

```

```{r football}
robotstxt::paths_allowed(paths = "/wiki/Miami_RedHawks_football", domain = "en.wikipedia.org", bot = "*")
```



```{r linkedin}
robotstxt::paths_allowed(paths = "/jobs/", domain = "www.linkedin.com", bot = "*")

```


```{r indeed}
robotstxt::paths_allowed(paths = "/jobs", domain = "www.indeed.com", bot = "*")
```




## 'rvest' demo: ISA coursebulletin

```{r rvest_demo}
isa_page_in_r = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/")

#extract the titles
#if all titles look the same on the page, it means they have the same tag/class,
#which would allow you to extract them all in one step
# we got the selected below by:
## [a] highlighted the course]
## [b] right clicked and selected inspect
## [c] found the part that was flushed containing the title
## [d] right clicked and copied the selector
## [e] Saw that the output from the got just got me the 24th course, so I dropped the ':nth-child(24)'

isa_page_in_r |>
  rvest::html_elements(
    "#sc_sccoursedescs > div > p.courseblocktitle > strong"
    ) |>
  rvest::html_text2() -> isa_titles
```

